<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Cities extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("cities")->truncate();

        DB::table("cities")->insert([
            ["name" => "Adilpur", "state_id" => 1],
            ["name" => "Badah", "state_id" => 1],
            ["name" => "Badin", "state_id" => 1],
            ["name" => "Bagarji", "state_id" => 1],
            ["name" => "Bakshshapur", "state_id" => 1],
            ["name" => "Bandhi", "state_id" => 1],
            ["name" => "Berani", "state_id" => 1],
            ["name" => "Bhan", "state_id" => 1],
            ["name" => "Bhiria City", "state_id" => 1],
            ["name" => "Bhiria Road", "state_id" => 1],
            ["name" => "Bhit Shah", "state_id" => 1],
            ["name" => "Bozdar", "state_id" => 1],
            ["name" => "Bulri", "state_id" => 1],
            ["name" => "Chak", "state_id" => 1],
            ["name" => "Chambar", "state_id" => 1],
            ["name" => "Chohar Jamali", "state_id" => 1],
            ["name" => "Chor", "state_id" => 1],
            ["name" => "Dadu", "state_id" => 1],
            ["name" => "Daharki", "state_id" => 1],
            ["name" => "Daro", "state_id" => 1],
            ["name" => "Darya Khan Mari", "state_id" => 1],
            ["name" => "Daulatpur", "state_id" => 1],
            ["name" => "Daur", "state_id" => 1],
            ["name" => "Dhoronaro", "state_id" => 1],
            ["name" => "Digri", "state_id" => 1],
            ["name" => "Diplo", "state_id" => 1],
            ["name" => "Dokri", "state_id" => 1],
            ["name" => "Faqirabad", "state_id" => 1],
            ["name" => "Gambat", "state_id" => 1],
            ["name" => "Garello", "state_id" => 1],
            ["name" => "Garhi Khairo", "state_id" => 1],
            ["name" => "Garhi Yasin", "state_id" => 1],
            ["name" => "Gharo", "state_id" => 1],
            ["name" => "Ghauspur", "state_id" => 1],
            ["name" => "Ghotki", "state_id" => 1],
            ["name" => "Golarchi", "state_id" => 1],
            ["name" => "Guddu", "state_id" => 1],
            ["name" => "Gulistan-E-Jauhar", "state_id" => 1],
            ["name" => "Hala", "state_id" => 1],
            ["name" => "Hingorja", "state_id" => 1],
            ["name" => "Hyderabad", "state_id" => 1],
            ["name" => "Islamkot", "state_id" => 1],
            ["name" => "Jacobabad", "state_id" => 1],
            ["name" => "Jam Nawaz Ali", "state_id" => 1],
            ["name" => "Jam Sahib", "state_id" => 1],
            ["name" => "Jati", "state_id" => 1],
            ["name" => "Jhol", "state_id" => 1],
            ["name" => "Jhudo", "state_id" => 1],
            ["name" => "Johi", "state_id" => 1],
            ["name" => "Kadhan", "state_id" => 1],
            ["name" => "Kambar", "state_id" => 1],
            ["name" => "Kandhra", "state_id" => 1],
            ["name" => "Kandiari", "state_id" => 1],
            ["name" => "Kandiaro", "state_id" => 1],
            ["name" => "Karachi", "state_id" => 1],
            ["name" => "Karampur", "state_id" => 1],
            ["name" => "Kario Ghanwar", "state_id" => 1],
            ["name" => "Karoondi", "state_id" => 1],
            ["name" => "Kashmor", "state_id" => 1],
            ["name" => "Kazi Ahmad", "state_id" => 1],
            ["name" => "Keti Bandar", "state_id" => 1],
            ["name" => "Khadro", "state_id" => 1],
            ["name" => "Khairpur", "state_id" => 1],
            ["name" => "Khairpur Nathan Shah", "state_id" => 1],
            ["name" => "Khandh Kot", "state_id" => 1],
            ["name" => "Khanpur", "state_id" => 1],
            ["name" => "Khipro", "state_id" => 1],
            ["name" => "Khoski", "state_id" => 1],
            ["name" => "Khuhra", "state_id" => 1],
            ["name" => "Khyber", "state_id" => 1],
            ["name" => "Kot Diji", "state_id" => 1],
            ["name" => "Kot Ghulam Mohammad", "state_id" => 1],
            ["name" => "Kotri", "state_id" => 1],
            ["name" => "Kumb", "state_id" => 1],
            ["name" => "Kunri", "state_id" => 1],
            ["name" => "Lakhi", "state_id" => 1],
            ["name" => "Larkana", "state_id" => 1],
            ["name" => "Madeji", "state_id" => 1],
            ["name" => "Matiari", "state_id" => 1],
            ["name" => "Matli", "state_id" => 1],
            ["name" => "Mehar", "state_id" => 1],
            ["name" => "Mehrabpur", "state_id" => 1],
            ["name" => "Miro Khan", "state_id" => 1],
            ["name" => "Mirpur Bathoro", "state_id" => 1],
            ["name" => "Mirpur Khas", "state_id" => 1],
            ["name" => "Mirpur Mathelo", "state_id" => 1],
            ["name" => "Mirpur Sakro", "state_id" => 1],
            ["name" => "Mirwah", "state_id" => 1],
            ["name" => "Mithi", "state_id" => 1],
            ["name" => "Moro", "state_id" => 1],
            ["name" => "Nabisar", "state_id" => 1],
            ["name" => "Nasarpur", "state_id" => 1],
            ["name" => "Nasirabad", "state_id" => 1],
            ["name" => "Naudero", "state_id" => 1],
            ["name" => "Naukot", "state_id" => 1],
            ["name" => "Naushahro Firoz", "state_id" => 1],
            ["name" => "Nawabshah", "state_id" => 1],
            ["name" => "Oderolal Station", "state_id" => 1],
            ["name" => "Pacca Chang", "state_id" => 1],
            ["name" => "Padidan", "state_id" => 1],
            ["name" => "Pano Aqil", "state_id" => 1],
            ["name" => "Perumal", "state_id" => 1],
            ["name" => "Phulji", "state_id" => 1],
            ["name" => "Pirjo Goth", "state_id" => 1],
            ["name" => "Piryaloi", "state_id" => 1],
            ["name" => "Pithoro", "state_id" => 1],
            ["name" => "Radhan", "state_id" => 1],
            ["name" => "Rajo Khanani", "state_id" => 1],
            ["name" => "Ranipur", "state_id" => 1],
            ["name" => "Ratodero", "state_id" => 1],
            ["name" => "Rohri", "state_id" => 1],
            ["name" => "Rustam", "state_id" => 1],
            ["name" => "Saeedabad", "state_id" => 1],
            ["name" => "Sakrand", "state_id" => 1],
            ["name" => "Samaro", "state_id" => 1],
            ["name" => "Sanghar", "state_id" => 1],
            ["name" => "Sann", "state_id" => 1],
            ["name" => "Sarhari", "state_id" => 1],
            ["name" => "Sehwan", "state_id" => 1],
            ["name" => "Setharja", "state_id" => 1],
            ["name" => "Shah Dipalli", "state_id" => 1],
            ["name" => "Shahdadkot", "state_id" => 1],
            ["name" => "Shahdadpur", "state_id" => 1],
            ["name" => "Shahpur Chakar", "state_id" => 1],
            ["name" => "Shahpur Jahania", "state_id" => 1],
            ["name" => "Shikarpur", "state_id" => 1],
            ["name" => "Sinjhoro", "state_id" => 1],
            ["name" => "Sita Road", "state_id" => 1],
            ["name" => "Sobhodero", "state_id" => 1],
            ["name" => "Sujawal", "state_id" => 1],
            ["name" => "Sukkur", "state_id" => 1],
            ["name" => "Talhar", "state_id" => 1],
            ["name" => "Tando Adam", "state_id" => 1],
            ["name" => "Tando Allah Yar", "state_id" => 1],
            ["name" => "Tando Bagho", "state_id" => 1],
            ["name" => "Tando Ghulam Ali", "state_id" => 1],
            ["name" => "Tando Jam", "state_id" => 1],
            ["name" => "Tando Jan Mohammad", "state_id" => 1],
            ["name" => "Tando Mitha Khan", "state_id" => 1],
            ["name" => "Tando Muhammad Khan", "state_id" => 1],
            ["name" => "Tangwani", "state_id" => 1],
            ["name" => "Thano Bula Khan", "state_id" => 1],
            ["name" => "Thari Mirwah", "state_id" => 1],
            ["name" => "Tharushah", "state_id" => 1],
            ["name" => "Thatta", "state_id" => 1],
            ["name" => "Ther I", "state_id" => 1],
            ["name" => "Ther I Mohabat", "state_id" => 1],
            ["name" => "Thul", "state_id" => 1],
            ["name" => "Ubauro", "state_id" => 1],
            ["name" => "Umarkot", "state_id" => 1],
            ["name" => "Warah", "state_id" => 1],
            ["name" => "Abohar", "state_id" => 2],
            ["name" => "Adampur", "state_id" => 2],
            ["name" => "Ahmedgarh", "state_id" => 2],
            ["name" => "Ajnala", "state_id" => 2],
            ["name" => "Akalgarh", "state_id" => 2],
            ["name" => "Alawalpur", "state_id" => 2],
            ["name" => "Amloh", "state_id" => 2],
            ["name" => "Amritsar", "state_id" => 2],
            ["name" => "Amritsar Cantonment", "state_id" => 2],
            ["name" => "Anandpur Sahib", "state_id" => 2],
            ["name" => "Badhni Kalan", "state_id" => 2],
            ["name" => "Bagh Purana", "state_id" => 2],
            ["name" => "Balachaur", "state_id" => 2],
            ["name" => "Banaur", "state_id" => 2],
            ["name" => "Banga", "state_id" => 2],
            ["name" => "Banur", "state_id" => 2],
            ["name" => "Baretta", "state_id" => 2],
            ["name" => "Bariwala", "state_id" => 2],
            ["name" => "Barnala", "state_id" => 2],
            ["name" => "Bassi Pathana", "state_id" => 2],
            ["name" => "Batala", "state_id" => 2],
            ["name" => "Bathinda", "state_id" => 2],
            ["name" => "Begowal", "state_id" => 2],
            ["name" => "Behrampur", "state_id" => 2],
            ["name" => "Bhabat", "state_id" => 2],
            ["name" => "Bhadur", "state_id" => 2],
            ["name" => "Bhankharpur", "state_id" => 2],
            ["name" => "Bharoli Kalan", "state_id" => 2],
            ["name" => "Bhawanigarh", "state_id" => 2],
            ["name" => "Bhikhi", "state_id" => 2],
            ["name" => "Bhikhiwind", "state_id" => 2],
            ["name" => "Bhisiana", "state_id" => 2],
            ["name" => "Bhogpur", "state_id" => 2],
            ["name" => "Bhuch", "state_id" => 2],
            ["name" => "Bhulath", "state_id" => 2],
            ["name" => "Budha Theh", "state_id" => 2],
            ["name" => "Budhlada", "state_id" => 2],
            ["name" => "Chima", "state_id" => 2],
            ["name" => "Chohal", "state_id" => 2],
            ["name" => "Dasuya", "state_id" => 2],
            ["name" => "Daulatpur", "state_id" => 2],
            ["name" => "Dera Baba Nanak", "state_id" => 2],
            ["name" => "Dera Bassi", "state_id" => 2],
            ["name" => "Dhanaula", "state_id" => 2],
            ["name" => "Dharam Kot", "state_id" => 2],
            ["name" => "Dhariwal", "state_id" => 2],
            ["name" => "Dhilwan", "state_id" => 2],
            ["name" => "Dhuri", "state_id" => 2],
            ["name" => "Dinanagar", "state_id" => 2],
            ["name" => "Dirba", "state_id" => 2],
            ["name" => "Doraha", "state_id" => 2],
            ["name" => "Faridkot", "state_id" => 2],
            ["name" => "Fateh Nangal", "state_id" => 2],
            ["name" => "Fatehgarh Churian", "state_id" => 2],
            ["name" => "Fatehgarh Sahib", "state_id" => 2],
            ["name" => "Fazilka", "state_id" => 2],
            ["name" => "Firozpur", "state_id" => 2],
            ["name" => "Firozpur Cantonment", "state_id" => 2],
            ["name" => "Gardhiwala", "state_id" => 2],
            ["name" => "Garhshankar", "state_id" => 2],
            ["name" => "Ghagga", "state_id" => 2],
            ["name" => "Ghanaur", "state_id" => 2],
            ["name" => "Giddarbaha", "state_id" => 2],
            ["name" => "Gobindgarh", "state_id" => 2],
            ["name" => "Goniana", "state_id" => 2],
            ["name" => "Goraya", "state_id" => 2],
            ["name" => "Gurdaspur", "state_id" => 2],
            ["name" => "Guru Har Sahai", "state_id" => 2],
            ["name" => "Hajipur", "state_id" => 2],
            ["name" => "Handiaya", "state_id" => 2],
            ["name" => "Hariana", "state_id" => 2],
            ["name" => "Hoshiarpur", "state_id" => 2],
            ["name" => "Hussainpur", "state_id" => 2],
            ["name" => "Jagraon", "state_id" => 2],
            ["name" => "Jaitu", "state_id" => 2],
            ["name" => "Jalalabad", "state_id" => 2],
            ["name" => "Jalandhar", "state_id" => 2],
            ["name" => "Jalandhar Cantonment", "state_id" => 2],
            ["name" => "Jandiala", "state_id" => 2],
            ["name" => "Jugial", "state_id" => 2],
            ["name" => "Kalanaur", "state_id" => 2],
            ["name" => "Kapurthala", "state_id" => 2],
            ["name" => "Karoran", "state_id" => 2],
            ["name" => "Kartarpur", "state_id" => 2],
            ["name" => "Khamanon", "state_id" => 2],
            ["name" => "Khanauri", "state_id" => 2],
            ["name" => "Khanna", "state_id" => 2],
            ["name" => "Kharar", "state_id" => 2],
            ["name" => "Khem Karan", "state_id" => 2],
            ["name" => "Kot Fatta", "state_id" => 2],
            ["name" => "Kot Isa Khan", "state_id" => 2],
            ["name" => "Kot Kapura", "state_id" => 2],
            ["name" => "Kotkapura", "state_id" => 2],
            ["name" => "Kurali", "state_id" => 2],
            ["name" => "Lalru", "state_id" => 2],
            ["name" => "Lehra Gaga", "state_id" => 2],
            ["name" => "Lodhian Khas", "state_id" => 2],
            ["name" => "Longowal", "state_id" => 2],
            ["name" => "Ludhiana", "state_id" => 2],
            ["name" => "Machhiwara", "state_id" => 2],
            ["name" => "Mahilpur", "state_id" => 2],
            ["name" => "Majitha", "state_id" => 2],
            ["name" => "Makhu", "state_id" => 2],
            ["name" => "Malaut", "state_id" => 2],
            ["name" => "Malerkotla", "state_id" => 2],
            ["name" => "Maloud", "state_id" => 2],
            ["name" => "Mandi Gobindgarh", "state_id" => 2],
            ["name" => "Mansa", "state_id" => 2],
            ["name" => "Maur", "state_id" => 2],
            ["name" => "Moga", "state_id" => 2],
            ["name" => "Mohali", "state_id" => 2],
            ["name" => "Moonak", "state_id" => 2],
            ["name" => "Morinda", "state_id" => 2],
            ["name" => "Mukerian", "state_id" => 2],
            ["name" => "Muktsar", "state_id" => 2],
            ["name" => "Mullanpur Dakha", "state_id" => 2],
            ["name" => "Mullanpur Garibdas", "state_id" => 2],
            ["name" => "Munak", "state_id" => 2],
            ["name" => "Muradpura", "state_id" => 2],
            ["name" => "Nabha", "state_id" => 2],
            ["name" => "Nakodar", "state_id" => 2],
            ["name" => "Nangal", "state_id" => 2],
            ["name" => "Nawashahr", "state_id" => 2],
            ["name" => "Naya Nangal", "state_id" => 2],
            ["name" => "Nehon", "state_id" => 2],
            ["name" => "Nurmahal", "state_id" => 2],
            ["name" => "Pathankot", "state_id" => 2],
            ["name" => "Patiala", "state_id" => 2],
            ["name" => "Patti", "state_id" => 2],
            ["name" => "Pattran", "state_id" => 2],
            ["name" => "Payal", "state_id" => 2],
            ["name" => "Phagwara", "state_id" => 2],
            ["name" => "Phillaur", "state_id" => 2],
            ["name" => "Qadian", "state_id" => 2],
            ["name" => "Rahon", "state_id" => 2],
            ["name" => "Raikot", "state_id" => 2],
            ["name" => "Raja Sansi", "state_id" => 2],
            ["name" => "Rajpura", "state_id" => 2],
            ["name" => "Ram Das", "state_id" => 2],
            ["name" => "Raman", "state_id" => 2],
            ["name" => "Rampura", "state_id" => 2],
            ["name" => "Rayya", "state_id" => 2],
            ["name" => "Rupnagar", "state_id" => 2],
            ["name" => "Rurki Kasba", "state_id" => 2],
            ["name" => "Sahnewal", "state_id" => 2],
            ["name" => "Samana", "state_id" => 2],
            ["name" => "Samrala", "state_id" => 2],
            ["name" => "Sanaur", "state_id" => 2],
            ["name" => "Sangat", "state_id" => 2],
            ["name" => "Sangrur", "state_id" => 2],
            ["name" => "Sansarpur", "state_id" => 2],
            ["name" => "Sardulgarh", "state_id" => 2],
            ["name" => "Shahkot", "state_id" => 2],
            ["name" => "Sham Churasi", "state_id" => 2],
            ["name" => "Shekhpura", "state_id" => 2],
            ["name" => "Sirhind", "state_id" => 2],
            ["name" => "Sri Hargobindpur", "state_id" => 2],
            ["name" => "Sujanpur", "state_id" => 2],
            ["name" => "Sultanpur Lodhi", "state_id" => 2],
            ["name" => "Sunam", "state_id" => 2],
            ["name" => "Talwandi Bhai", "state_id" => 2],
            ["name" => "Talwara", "state_id" => 2],
            ["name" => "Tappa", "state_id" => 2],
            ["name" => "Tarn Taran", "state_id" => 2],
            ["name" => "Urmar Tanda", "state_id" => 2],
            ["name" => "Zira", "state_id" => 2],
            ["name" => "Zirakpur", "state_id" => 2],
            ["name" => "Abdul Hakim", "state_id" => 2],
            ["name" => "Ahmadpur East", "state_id" => 2],
            ["name" => "Ahmadpur Lumma", "state_id" => 2],
            ["name" => "Ahmadpur Sial", "state_id" => 2],
            ["name" => "Ahmedabad", "state_id" => 2],
            ["name" => "Alipur", "state_id" => 2],
            ["name" => "Alipur Chatha", "state_id" => 2],
            ["name" => "Arifwala", "state_id" => 2],
            ["name" => "Attock", "state_id" => 2],
            ["name" => "Baddomalhi", "state_id" => 2],
            ["name" => "Bagh", "state_id" => 2],
            ["name" => "Bahawalnagar", "state_id" => 2],
            ["name" => "Bahawalpur", "state_id" => 2],
            ["name" => "Bai Pheru", "state_id" => 2],
            ["name" => "Basirpur", "state_id" => 2],
            ["name" => "Begowala", "state_id" => 2],
            ["name" => "Bhakkar", "state_id" => 2],
            ["name" => "Bhalwal", "state_id" => 2],
            ["name" => "Bhawana", "state_id" => 2],
            ["name" => "Bhera", "state_id" => 2],
            ["name" => "Bhopalwala", "state_id" => 2],
            ["name" => "Burewala", "state_id" => 2],
            ["name" => "Chak Azam Sahu", "state_id" => 2],
            ["name" => "Chak Jhumra", "state_id" => 2],
            ["name" => "Chak Sarwar Shahid", "state_id" => 2],
            ["name" => "Chakwal", "state_id" => 2],
            ["name" => "Chawinda", "state_id" => 2],
            ["name" => "Chichawatni", "state_id" => 2],
            ["name" => "Chiniot", "state_id" => 2],
            ["name" => "Chishtian Mandi", "state_id" => 2],
            ["name" => "Choa Saidan Shah", "state_id" => 2],
            ["name" => "Chuhar Kana", "state_id" => 2],
            ["name" => "Chunian", "state_id" => 2],
            ["name" => "Dajal", "state_id" => 2],
            ["name" => "Darya Khan", "state_id" => 2],
            ["name" => "Daska", "state_id" => 2],
            ["name" => "Daud Khel", "state_id" => 2],
            ["name" => "Daultala", "state_id" => 2],
            ["name" => "Dera Din Panah", "state_id" => 2],
            ["name" => "Dera Ghazi Khan", "state_id" => 2],
            ["name" => "Dhanote", "state_id" => 2],
            ["name" => "Dhonkal", "state_id" => 2],
            ["name" => "Dijkot", "state_id" => 2],
            ["name" => "Dina", "state_id" => 2],
            ["name" => "Dinga", "state_id" => 2],
            ["name" => "Dipalpur", "state_id" => 2],
            ["name" => "Dullewala", "state_id" => 2],
            ["name" => "Dunga Bunga", "state_id" => 2],
            ["name" => "Dunyapur", "state_id" => 2],
            ["name" => "Eminabad", "state_id" => 2],
            ["name" => "Faisalabad", "state_id" => 2],
            ["name" => "Faqirwali", "state_id" => 2],
            ["name" => "Faruka", "state_id" => 2],
            ["name" => "Fateh Jang", "state_id" => 2],
            ["name" => "Fatehpur", "state_id" => 2],
            ["name" => "Fazalpur", "state_id" => 2],
            ["name" => "Ferozwala", "state_id" => 2],
            ["name" => "Fort Abbas", "state_id" => 2],
            ["name" => "Garh Maharaja", "state_id" => 2],
            ["name" => "Ghakar", "state_id" => 2],
            ["name" => "Ghurgushti", "state_id" => 2],
            ["name" => "Gojra", "state_id" => 2],
            ["name" => "Gujar Khan", "state_id" => 2],
            ["name" => "Gujranwala", "state_id" => 2],
            ["name" => "Gujrat", "state_id" => 2],
            ["name" => "Hadali", "state_id" => 2],
            ["name" => "Hafizabad", "state_id" => 2],
            ["name" => "Harnoli", "state_id" => 2],
            ["name" => "Harunabad", "state_id" => 2],
            ["name" => "Hasan Abdal", "state_id" => 2],
            ["name" => "Hasilpur", "state_id" => 2],
            ["name" => "Haveli", "state_id" => 2],
            ["name" => "Hazro", "state_id" => 2],
            ["name" => "Hujra Shah Muqim", "state_id" => 2],
            ["name" => "Isa Khel", "state_id" => 2],
            ["name" => "Jahanian", "state_id" => 2],
            ["name" => "Jalalpur Bhattian", "state_id" => 2],
            ["name" => "Jalalpur Jattan", "state_id" => 2],
            ["name" => "Jalalpur Pirwala", "state_id" => 2],
            ["name" => "Jalla Jeem", "state_id" => 2],
            ["name" => "Jamke Chima", "state_id" => 2],
            ["name" => "Jampur", "state_id" => 2],
            ["name" => "Jand", "state_id" => 2],
            ["name" => "Jandanwala", "state_id" => 2],
            ["name" => "Jandiala Sherkhan", "state_id" => 2],
            ["name" => "Jaranwala", "state_id" => 2],
            ["name" => "Jatoi", "state_id" => 2],
            ["name" => "Jauharabad", "state_id" => 2],
            ["name" => "Jhang", "state_id" => 2],
            ["name" => "Jhawarian", "state_id" => 2],
            ["name" => "Jhelum", "state_id" => 2],
            ["name" => "Kabirwala", "state_id" => 2],
            ["name" => "Kahna Nau", "state_id" => 2],
            ["name" => "Kahror Pakka", "state_id" => 2],
            ["name" => "Kahuta", "state_id" => 2],
            ["name" => "Kalabagh", "state_id" => 2],
            ["name" => "Kalaswala", "state_id" => 2],
            ["name" => "Kaleke", "state_id" => 2],
            ["name" => "Kalur Kot", "state_id" => 2],
            ["name" => "Kamalia", "state_id" => 2],
            ["name" => "Kamar Mashani", "state_id" => 2],
            ["name" => "Kamir", "state_id" => 2],
            ["name" => "Kamoke", "state_id" => 2],
            ["name" => "Kamra", "state_id" => 2],
            ["name" => "Kanganpur", "state_id" => 2],
            ["name" => "Karampur", "state_id" => 2],
            ["name" => "Karor Lal Esan", "state_id" => 2],
            ["name" => "Kasur", "state_id" => 2],
            ["name" => "Khairpur Tamewali", "state_id" => 2],
            ["name" => "Khanewal", "state_id" => 2],
            ["name" => "Khangah Dogran", "state_id" => 2],
            ["name" => "Khangarh", "state_id" => 2],
            ["name" => "Khanpur", "state_id" => 2],
            ["name" => "Kharian", "state_id" => 2],
            ["name" => "Khewra", "state_id" => 2],
            ["name" => "Khundian", "state_id" => 2],
            ["name" => "Khurianwala", "state_id" => 2],
            ["name" => "Khushab", "state_id" => 2],
            ["name" => "Kot Abdul Malik", "state_id" => 2],
            ["name" => "Kot Addu", "state_id" => 2],
            ["name" => "Kot Mithan", "state_id" => 2],
            ["name" => "Kot Moman", "state_id" => 2],
            ["name" => "Kot Radha Kishan", "state_id" => 2],
            ["name" => "Kot Samaba", "state_id" => 2],
            ["name" => "Kotli Loharan", "state_id" => 2],
            ["name" => "Kundian", "state_id" => 2],
            ["name" => "Kunjah", "state_id" => 2],
            ["name" => "Lahore", "state_id" => 2],
            ["name" => "Lalamusa", "state_id" => 2],
            ["name" => "Lalian", "state_id" => 2],
            ["name" => "Liaqatabad", "state_id" => 2],
            ["name" => "Liaqatpur", "state_id" => 2],
            ["name" => "Lieah", "state_id" => 2],
            ["name" => "Liliani", "state_id" => 2],
            ["name" => "Lodhran", "state_id" => 2],
            ["name" => "Ludhewala Waraich", "state_id" => 2],
            ["name" => "Mailsi", "state_id" => 2],
            ["name" => "Makhdumpur", "state_id" => 2],
            ["name" => "Makhdumpur Rashid", "state_id" => 2],
            ["name" => "Malakwal", "state_id" => 2],
            ["name" => "Mamu Kanjan", "state_id" => 2],
            ["name" => "Mananwala Jodh Singh", "state_id" => 2],
            ["name" => "Mandi Bahauddin", "state_id" => 2],
            ["name" => "Mandi Sadiq Ganj", "state_id" => 2],
            ["name" => "Mangat", "state_id" => 2],
            ["name" => "Mangla", "state_id" => 2],
            ["name" => "Mankera", "state_id" => 2],
            ["name" => "Mian Channun", "state_id" => 2],
            ["name" => "Miani", "state_id" => 2],
            ["name" => "Mianwali", "state_id" => 2],
            ["name" => "Minchinabad", "state_id" => 2],
            ["name" => "Mitha Tiwana", "state_id" => 2],
            ["name" => "Multan", "state_id" => 2],
            ["name" => "Muridke", "state_id" => 2],
            ["name" => "Murree", "state_id" => 2],
            ["name" => "Mustafabad", "state_id" => 2],
            ["name" => "Muzaffargarh", "state_id" => 2],
            ["name" => "Nankana Sahib", "state_id" => 2],
            ["name" => "Narang", "state_id" => 2],
            ["name" => "Narowal", "state_id" => 2],
            ["name" => "Noorpur Thal", "state_id" => 2],
            ["name" => "Nowshera", "state_id" => 2],
            ["name" => "Nowshera Virkan", "state_id" => 2],
            ["name" => "Okara", "state_id" => 2],
            ["name" => "Pakpattan", "state_id" => 2],
            ["name" => "Pasrur", "state_id" => 2],
            ["name" => "Pattoki", "state_id" => 2],
            ["name" => "Phalia", "state_id" => 2],
            ["name" => "Phularwan", "state_id" => 2],
            ["name" => "Pind Dadan Khan", "state_id" => 2],
            ["name" => "Pindi Bhattian", "state_id" => 2],
            ["name" => "Pindi Gheb", "state_id" => 2],
            ["name" => "Pirmahal", "state_id" => 2],
            ["name" => "Qadirabad", "state_id" => 2],
            ["name" => "Qadirpur Ran", "state_id" => 2],
            ["name" => "Qila Disar Singh", "state_id" => 2],
            ["name" => "Qila Sobha Singh", "state_id" => 2],
            ["name" => "Quaidabad", "state_id" => 2],
            ["name" => "Rabwah", "state_id" => 2],
            ["name" => "Rahim Yar Khan", "state_id" => 2],
            ["name" => "Raiwind", "state_id" => 2],
            ["name" => "Raja Jang", "state_id" => 2],
            ["name" => "Rajanpur", "state_id" => 2],
            ["name" => "Rasulnagar", "state_id" => 2],
            ["name" => "Rawalpindi", "state_id" => 2],
            ["name" => "Renala Khurd", "state_id" => 2],
            ["name" => "Rojhan", "state_id" => 2],
            ["name" => "Saddar Gogera", "state_id" => 2],
            ["name" => "Sadiqabad", "state_id" => 2],
            ["name" => "Safdarabad", "state_id" => 2],
            ["name" => "Sahiwal", "state_id" => 2],
            ["name" => "Samasatta", "state_id" => 2],
            ["name" => "Sambrial", "state_id" => 2],
            ["name" => "Sammundri", "state_id" => 2],
            ["name" => "Sangala Hill", "state_id" => 2],
            ["name" => "Sanjwal", "state_id" => 2],
            ["name" => "Sarai Alamgir", "state_id" => 2],
            ["name" => "Sarai Sidhu", "state_id" => 2],
            ["name" => "Sargodha", "state_id" => 2],
            ["name" => "Shadiwal", "state_id" => 2],
            ["name" => "Shahkot", "state_id" => 2],
            ["name" => "Shahpur City", "state_id" => 2],
            ["name" => "Shahpur Saddar", "state_id" => 2],
            ["name" => "Shakargarh", "state_id" => 2],
            ["name" => "Sharqpur", "state_id" => 2],
            ["name" => "Shehr Sultan", "state_id" => 2],
            ["name" => "Shekhupura", "state_id" => 2],
            ["name" => "Shujaabad", "state_id" => 2],
            ["name" => "Sialkot", "state_id" => 2],
            ["name" => "Sillanwali", "state_id" => 2],
            ["name" => "Sodhra", "state_id" => 2],
            ["name" => "Sohawa", "state_id" => 2],
            ["name" => "Sukheke", "state_id" => 2],
            ["name" => "Talagang", "state_id" => 2],
            ["name" => "Tandlianwala", "state_id" => 2],
            ["name" => "Taunsa", "state_id" => 2],
            ["name" => "Taxila", "state_id" => 2],
            ["name" => "Tibba Sultanpur", "state_id" => 2],
            ["name" => "Toba Tek Singh", "state_id" => 2],
            ["name" => "Tulamba", "state_id" => 2],
            ["name" => "Uch", "state_id" => 2],
            ["name" => "Vihari", "state_id" => 2],
            ["name" => "Wah", "state_id" => 2],
            ["name" => "Warburton", "state_id" => 2],
            ["name" => "Wazirabad", "state_id" => 2],
            ["name" => "Yazman", "state_id" => 2],
            ["name" => "Zafarwal", "state_id" => 2],
            ["name" => "Zahir Pir", "state_id" => 2],
            ["name" => "Barkhan", "state_id" => 3],
            ["name" => "Bela", "state_id" => 3],
            ["name" => "Bhag", "state_id" => 3],
            ["name" => "Chaman", "state_id" => 3],
            ["name" => "Chitkan", "state_id" => 3],
            ["name" => "Dalbandin", "state_id" => 3],
            ["name" => "Dera Allah Yar", "state_id" => 3],
            ["name" => "Dera Bugti", "state_id" => 3],
            ["name" => "Dera Murad Jamali", "state_id" => 3],
            ["name" => "Dhadar", "state_id" => 3],
            ["name" => "Duki", "state_id" => 3],
            ["name" => "Gaddani", "state_id" => 3],
            ["name" => "Gwadar", "state_id" => 3],
            ["name" => "Harnai", "state_id" => 3],
            ["name" => "Hub", "state_id" => 3],
            ["name" => "Jiwani", "state_id" => 3],
            ["name" => "Kalat", "state_id" => 3],
            ["name" => "Kharan", "state_id" => 3],
            ["name" => "Khuzdar", "state_id" => 3],
            ["name" => "Kohlu", "state_id" => 3],
            ["name" => "Loralai", "state_id" => 3],
            ["name" => "Mach", "state_id" => 3],
            ["name" => "Mastung", "state_id" => 3],
            ["name" => "Nushki", "state_id" => 3],
            ["name" => "Ormara", "state_id" => 3],
            ["name" => "Pasni", "state_id" => 3],
            ["name" => "Pishin", "state_id" => 3],
            ["name" => "Quetta", "state_id" => 3],
            ["name" => "Sibi", "state_id" => 3],
            ["name" => "Sohbatpur", "state_id" => 3],
            ["name" => "Surab", "state_id" => 3],
            ["name" => "Turbat", "state_id" => 3],
            ["name" => "Usta Muhammad", "state_id" => 3],
            ["name" => "Uthal", "state_id" => 3],
            ["name" => "Wadh", "state_id" => 3],
            ["name" => "Winder", "state_id" => 3],
            ["name" => "Zehri", "state_id" => 3],
            ["name" => "Zhob", "state_id" => 3],
            ["name" => "Ziarat", "state_id" => 3],
            ["name" => "Peshawar", "state_id" => 4],
            ["name" => "Mardan", "state_id" => 4],
            ["name" => "Mingora", "state_id" => 4],
            ["name" => "Kohat", "state_id" => 4],
            ["name" => "Dera Ismail Khan", "state_id" => 4],
            ["name" => "Abbottabad", "state_id" => 4],
            ["name" => "Mansehra", "state_id" => 4],
            ["name" => "Swabi", "state_id" => 4],
            ["name" => "Nowshera", "state_id" => 4],
            ["name" => "Kabal", "state_id" => 4],
            ["name" => "Charsadda", "state_id" => 4],
            ["name" => "Barikot", "state_id" => 4],
            ["name" => "Shabqadar", "state_id" => 4],
            ["name" => "Haripur", "state_id" => 4],
            ["name" => "Takht-i-Bahi", "state_id" => 4],
            ["name" => "Paharpur", "state_id" => 4],
            ["name" => "Batkhela", "state_id" => 4],
            ["name" => "Jamrud", "state_id" => 4],
            ["name" => "Bahrain", "state_id" => 4],
            ["name" => "Lakki Marwat", "state_id" => 4],
            ["name" => "Pabbi", "state_id" => 4],
            ["name" => "Topi", "state_id" => 4],
            ["name" => "Jehangira", "state_id" => 4],
            ["name" => "Karak", "state_id" => 4],
            ["name" => "Bannu", "state_id" => 4],
            ["name" => "Chitral", "state_id" => 4],
            ["name" => "Hangu", "state_id" => 4],
            ["name" => "Havelian", "state_id" => 4],
            ["name" => "Khwazakhela", "state_id" => 4],
            ["name" => "Khalabat", "state_id" => 4],
            ["name" => "Tank", "state_id" => 4],
            ["name" => "Dir", "state_id" => 4],
            ["name" => "Matta", "state_id" => 4],
            ["name" => "Tordher", "state_id" => 4],
            ["name" => "Timargara", "state_id" => 4],
            ["name" => "Paroa", "state_id" => 4],
            ["name" => "Amangarh", "state_id" => 4],
            ["name" => "Risalpur", "state_id" => 4],
            ["name" => "Nawan Shehr", "state_id" => 4],
            ["name" => "Sadda", "state_id" => 4],
            ["name" => "Landi Kotal", "state_id" => 4],
            ["name" => "Tangi", "state_id" => 4],
            ["name" => "Akora Khattak", "state_id" => 4],
            ["name" => "Tall", "state_id" => 4],
            ["name" => "Zaida", "state_id" => 4],
            ["name" => "Islamabad", "state_id" => 5],
            ["name" => "Gilgit", "state_id" => 6],
            ["name" => "Skardu", "state_id" => 6],
            ["name" => "Khaplu", "state_id" => 6],
            ["name" => "Dambudas", "state_id" => 6],
            ["name" => "Tolti", "state_id" => 6],
            ["name" => "Eidghah", "state_id" => 6],
            ["name" => "Shigar", "state_id" => 6],
            ["name" => "Nagarkhas", "state_id" => 6],
            ["name" => "Ishkoman", "state_id" => 6],
            ["name" => "Juglot", "state_id" => 6],
            ["name" => "Danyor", "state_id" => 6],
            ["name" => "Karimabad", "state_id" => 6],
            ["name" => "Aliabad", "state_id" => 6],
            ["name" => "Chilas", "state_id" => 6],
            ["name" => "Gahkuch", "state_id" => 6],
            ["name" => "Tangir", "state_id" => 6],
            ["name" => "Mirpur", "state_id" => 7],
            ["name" => "Kotli", "state_id" => 7],
            ["name" => "Bhimber", "state_id" => 7],
            ["name" => "Muzaffarabad", "state_id" => 7],
            ["name" => "Hattian", "state_id" => 7],
            ["name" => "Neelam Valley", "state_id" => 7],
            ["name" => "Poonch", "state_id" => 7],
            ["name" => "Haveli", "state_id" => 7],
            ["name" => "Bagh", "state_id" => 7],
            ["name" => "Sudhanoti", "state_id" => 7],

            ["name" => "Glenfield", "state_id" => 8],
            ["name" => "Henderson", "state_id" => 8],
            ["name" => "Milford", "state_id" => 8],
            ["name" => "Balgowlah", "state_id" => 9],
            ["name" => "Balmain", "state_id" => 10],
            ["name" => "Bankstown", "state_id" => 11],
            ["name" => "Camberwell", "state_id" => 12],
            ["name" => "Caulfield", "state_id" => 13],
            ["name" => "Chatswood", "state_id" => 14],
            ["name" => "Cheltenham", "state_id" => 15],
            ["name" => "Cherrybrook", "state_id" => 16],
            ["name" => "Clayton", "state_id" => 17],
            ["name" => "Collingwood", "state_id" => 18],
            ["name" => "Hawthorn", "state_id" => 19],
            ["name" => "Jannnali", "state_id" => 20],
            ["name" => "Knoxfield", "state_id" => 21],
            ["name" => "Melbourne", "state_id" => 22],
            ["name" => "South Oakleigh", "state_id" => 22],
            ["name" => "Cottesole", "state_id" => 23],
            ["name" => "Darch", "state_id" => 23],
            ["name" => "Mullaloo", "state_id" => 23],
            ["name" => "Noranda", "state_id" => 23],
            ["name" => "Osborne Park", "state_id" => 23],
            ["name" => "Willetton", "state_id" => 23],
            ["name" => "Acacia Ridge", "state_id" => 24],
            ["name" => "Aitkenvale", "state_id" => 24],
            ["name" => "Alderley", "state_id" => 24],
            ["name" => "Alexander Hills", "state_id" => 24],
            ["name" => "Archerfield", "state_id" => 24],
            ["name" => "Ashmore", "state_id" => 24],
            ["name" => "Atherton", "state_id" => 24],
            ["name" => "Ayr", "state_id" => 24],
            ["name" => "Beachmere", "state_id" => 24],
            ["name" => "Beenleigh", "state_id" => 24],
            ["name" => "Beerwah", "state_id" => 24],
            ["name" => "Bell", "state_id" => 24],
            ["name" => "Belmont", "state_id" => 24],
            ["name" => "Biloela", "state_id" => 24],
            ["name" => "Birkdale", "state_id" => 24],
            ["name" => "Blackwater", "state_id" => 24],
            ["name" => "Bongaree", "state_id" => 24],
            ["name" => "Bonogin", "state_id" => 24],
            ["name" => "Boonah", "state_id" => 24],
            ["name" => "Bowen", "state_id" => 24],
            ["name" => "Brendale", "state_id" => 24],
            ["name" => "Brisbane", "state_id" => 24],
            ["name" => "Buddina", "state_id" => 24],
            ["name" => "Buderim", "state_id" => 24],
            ["name" => "Bundaberg", "state_id" => 24],
            ["name" => "Bundall", "state_id" => 24],
            ["name" => "Burleigh Heads", "state_id" => 24],
            ["name" => "Burpengary", "state_id" => 24],
            ["name" => "Cabaland", "state_id" => 24],
            ["name" => "Caboolture", "state_id" => 24],
            ["name" => "Cairns", "state_id" => 24],
            ["name" => "Cairns Northern Beaches", "state_id" => 24],
            ["name" => "Caloundra", "state_id" => 24],
            ["name" => "Capalaba", "state_id" => 24],
            ["name" => "Charters Towers", "state_id" => 24],
            ["name" => "Childers", "state_id" => 24],
            ["name" => "Cleveland", "state_id" => 24],
            ["name" => "Coolum Beach", "state_id" => 24],
            ["name" => "Coopers Plain", "state_id" => 24],
            ["name" => "Dalby", "state_id" => 24],
            ["name" => "Deception Bay", "state_id" => 24],
            ["name" => "Eagle Farm", "state_id" => 24],
            ["name" => "Eagleby", "state_id" => 24],
            ["name" => "Emerald", "state_id" => 24],
            ["name" => "Emundi", "state_id" => 24],
            ["name" => "Forest Lake", "state_id" => 24],
            ["name" => "Gatton", "state_id" => 24],
            ["name" => "Gladstone", "state_id" => 24],
            ["name" => "Gold Coast", "state_id" => 24],
            ["name" => "Gowrie Junction", "state_id" => 24],
            ["name" => "Gympie", "state_id" => 24],
            ["name" => "Helensvale", "state_id" => 24],
            ["name" => "Hervey Bay", "state_id" => 24],
            ["name" => "Ingham", "state_id" => 24],
            ["name" => "Innisfail", "state_id" => 24],
            ["name" => "Ipswich", "state_id" => 24],
            ["name" => "Jindalee", "state_id" => 24],
            ["name" => "Julatten", "state_id" => 24],
            ["name" => "Kawana Waters", "state_id" => 24],
            ["name" => "Kingaroy", "state_id" => 24],
            ["name" => "Lawnton", "state_id" => 24],
            ["name" => "Loganholme", "state_id" => 24],
            ["name" => "Mackay", "state_id" => 24],
            ["name" => "Mareeba", "state_id" => 24],
            ["name" => "Maroochydore", "state_id" => 24],
            ["name" => "Maroochydore-Mooloolaba", "state_id" => 24],
            ["name" => "Maryborough", "state_id" => 24],
            ["name" => "Miami", "state_id" => 24],
            ["name" => "Milton", "state_id" => 24],
            ["name" => "Molendinar", "state_id" => 24],
            ["name" => "Moranbah", "state_id" => 24],
            ["name" => "Morayfield", "state_id" => 24],
            ["name" => "Mossman", "state_id" => 24],
            ["name" => "Mount Glorious", "state_id" => 24],
            ["name" => "Mount Isa", "state_id" => 24],
            ["name" => "Murarrie", "state_id" => 24],
            ["name" => "Nairand Kay", "state_id" => 24],
            ["name" => "Nambour", "state_id" => 24],
            ["name" => "Nerang", "state_id" => 24],
            ["name" => "Nobby Beach", "state_id" => 24],
            ["name" => "Noosa Heads", "state_id" => 24],
            ["name" => "Noosaville", "state_id" => 24],
            ["name" => "Paddington", "state_id" => 24],
            ["name" => "Port Douglas", "state_id" => 24],
            ["name" => "Robina", "state_id" => 24],
            ["name" => "Rockhampton", "state_id" => 24],
            ["name" => "Rocklea", "state_id" => 24],
            ["name" => "Roma", "state_id" => 24],
            ["name" => "Rubyvale", "state_id" => 24],
            ["name" => "Sanctuary Cove", "state_id" => 24],
            ["name" => "Slade Point", "state_id" => 24],
            ["name" => "Southport", "state_id" => 24],
            ["name" => "Suburb", "state_id" => 24],
            ["name" => "Sunshine Coast", "state_id" => 24],
            ["name" => "Tewantin-Noosa", "state_id" => 24],
            ["name" => "The Summit", "state_id" => 24],
            ["name" => "Toowong", "state_id" => 24],
            ["name" => "Toowoomba", "state_id" => 24],
            ["name" => "Townsville", "state_id" => 24],
            ["name" => "Victoria Point", "state_id" => 24],
            ["name" => "Warwick", "state_id" => 24],
            ["name" => "Willawong", "state_id" => 24],
            ["name" => "Yatala", "state_id" => 24],
            ["name" => "Yeppoon", "state_id" => 24],
            ["name" => "Zillmere", "state_id" => 24],
            ["name" => "Bridgewater-Gagebrook", "state_id" => 25],
            ["name" => "Burnie", "state_id" => 25],
            ["name" => "Burnie-Devonport", "state_id" => 25],
            ["name" => "Glenorchy", "state_id" => 25],
            ["name" => "Hobart", "state_id" => 25],
            ["name" => "Kingston-Blackmans Bay", "state_id" => 25],
            ["name" => "Launceston", "state_id" => 25],
            ["name" => "New Norfolk", "state_id" => 25],
            ["name" => "Rowella", "state_id" => 25],
            ["name" => "Sheffield", "state_id" => 25],
            ["name" => "Ulverstone", "state_id" => 25],
            ["name" => "Templestowe", "state_id" => 26],
            ["name" => "Albion", "state_id" => 27],
            ["name" => "Ararat", "state_id" => 27],
            ["name" => "Avenel", "state_id" => 27],
            ["name" => "Avondale Heights", "state_id" => 27],
            ["name" => "Baccus Marsh", "state_id" => 27],
            ["name" => "Bairnsdale", "state_id" => 27],
            ["name" => "Ballarat", "state_id" => 27],
            ["name" => "Balwyn", "state_id" => 27],
            ["name" => "Batman", "state_id" => 27],
            ["name" => "Bayswater", "state_id" => 27],
            ["name" => "Belmont", "state_id" => 27],
            ["name" => "Benalla", "state_id" => 27],
            ["name" => "Bendigo", "state_id" => 27],
            ["name" => "Bentleigh East", "state_id" => 27],
            ["name" => "Berwick", "state_id" => 27],
            ["name" => "Blackburn", "state_id" => 27],
            ["name" => "Blue Mountains", "state_id" => 27],
            ["name" => "Boonah", "state_id" => 27],
            ["name" => "Boronia", "state_id" => 27],
            ["name" => "Box Hill", "state_id" => 27],
            ["name" => "Brighton East", "state_id" => 27],
            ["name" => "Bundoora", "state_id" => 27],
            ["name" => "Campbellfield", "state_id" => 27],
            ["name" => "Carlton South", "state_id" => 27],
            ["name" => "Caroline Springs", "state_id" => 27],
            ["name" => "Castle Hill", "state_id" => 27],
            ["name" => "Castlemaine", "state_id" => 27],
            ["name" => "Caulfield", "state_id" => 27],
            ["name" => "Cheltenham", "state_id" => 27],
            ["name" => "Chester", "state_id" => 27],
            ["name" => "Clayton South", "state_id" => 27],
            ["name" => "Clifton Springs", "state_id" => 27],
            ["name" => "Coburg", "state_id" => 27],
            ["name" => "Colac", "state_id" => 27],
            ["name" => "Collingwood", "state_id" => 27],
            ["name" => "Craigieburn", "state_id" => 27],
            ["name" => "Cranbourne", "state_id" => 27],
            ["name" => "Crib Point", "state_id" => 27],
            ["name" => "Dandenong", "state_id" => 27],
            ["name" => "Devon Meadows", "state_id" => 27],
            ["name" => "Diamond Creek", "state_id" => 27],
            ["name" => "Doncaster East", "state_id" => 27],
            ["name" => "Doncester", "state_id" => 27],
            ["name" => "Donvale", "state_id" => 27],
            ["name" => "Echuca-Moama", "state_id" => 27],
            ["name" => "Elsternwick", "state_id" => 27],
            ["name" => "Eltham", "state_id" => 27],
            ["name" => "Fairfield", "state_id" => 27],
            ["name" => "Fitzroy", "state_id" => 27],
            ["name" => "Frnakston", "state_id" => 27],
            ["name" => "Geelong", "state_id" => 27],
            ["name" => "Glen Waverley", "state_id" => 27],
            ["name" => "Glenorchy", "state_id" => 27],
            ["name" => "Hallam", "state_id" => 27],
            ["name" => "Hamilton", "state_id" => 27],
            ["name" => "Hastings", "state_id" => 27],
            ["name" => "Healesville", "state_id" => 27],
            ["name" => "Horsham", "state_id" => 27],
            ["name" => "Hughesdale", "state_id" => 27],
            ["name" => "Ivanhoe", "state_id" => 27],
            ["name" => "Keilor", "state_id" => 27],
            ["name" => "Kensington", "state_id" => 27],
            ["name" => "Kerang", "state_id" => 27],
            ["name" => "Kilmore", "state_id" => 27],
            ["name" => "Kilsyth", "state_id" => 27],
            ["name" => "Kyabram", "state_id" => 27],
            ["name" => "Lakes Entrance", "state_id" => 27],
            ["name" => "Lalor", "state_id" => 27],
            ["name" => "Lara", "state_id" => 27],
            ["name" => "Laverton North", "state_id" => 27],
            ["name" => "Leopold", "state_id" => 27],
            ["name" => "Lower Templestowe", "state_id" => 27],
            ["name" => "Maidstone", "state_id" => 27],
            ["name" => "Malvern", "state_id" => 27],
            ["name" => "Maryborough", "state_id" => 27],
            ["name" => "Melbourne", "state_id" => 27],
            ["name" => "Melton", "state_id" => 27],
            ["name" => "Middle Park", "state_id" => 27],
            ["name" => "Mildura", "state_id" => 27],
            ["name" => "Mitcham", "state_id" => 27],
            ["name" => "Moe-Yallourn", "state_id" => 27],
            ["name" => "Moorabbin", "state_id" => 27],
            ["name" => "Mordialloc", "state_id" => 27],
            ["name" => "Morwell", "state_id" => 27],
            ["name" => "Mulgrave", "state_id" => 27],
            ["name" => "Murrumbeena", "state_id" => 27],
            ["name" => "Neerim South", "state_id" => 27],
            ["name" => "Noble Park North", "state_id" => 27],
            ["name" => "Notting Hill", "state_id" => 27],
            ["name" => "Oak Park", "state_id" => 27],
            ["name" => "Ocean Grove-Barwon Heads", "state_id" => 27],
            ["name" => "Olinda", "state_id" => 27],
            ["name" => "Pakenham", "state_id" => 27],
            ["name" => "Park Orchards", "state_id" => 27],
            ["name" => "Port Melbourne", "state_id" => 27],
            ["name" => "Portland", "state_id" => 27],
            ["name" => "Prahran", "state_id" => 27],
            ["name" => "Preston", "state_id" => 27],
            ["name" => "Pritbourne", "state_id" => 27],
            ["name" => "Queenscliff", "state_id" => 27],
            ["name" => "Reservoir", "state_id" => 27],
            ["name" => "Ringwood", "state_id" => 27],
            ["name" => "Rowville", "state_id" => 27],
            ["name" => "Sale", "state_id" => 27],
            ["name" => "Sandringham", "state_id" => 27],
            ["name" => "Scoresby", "state_id" => 27],
            ["name" => "Sebastopol", "state_id" => 27],
            ["name" => "Seymour", "state_id" => 27],
            ["name" => "Shepparton-Mooroopna", "state_id" => 27],
            ["name" => "Somerville", "state_id" => 27],
            ["name" => "South Yarra", "state_id" => 27],
            ["name" => "Southbank", "state_id" => 27],
            ["name" => "St. Albans", "state_id" => 27],
            ["name" => "St. Kilda East", "state_id" => 27],
            ["name" => "Stawell", "state_id" => 27],
            ["name" => "Sunbury", "state_id" => 27],
            ["name" => "Sunshine West", "state_id" => 27],
            ["name" => "Swan Hill", "state_id" => 27],
            ["name" => "Tatura", "state_id" => 27],
            ["name" => "Thomastown", "state_id" => 27],
            ["name" => "Thornbury", "state_id" => 27],
            ["name" => "Tongala", "state_id" => 27],
            ["name" => "Torquay", "state_id" => 27],
            ["name" => "Traralgon", "state_id" => 27],
            ["name" => "Tullamarine", "state_id" => 27],
            ["name" => "Vermont", "state_id" => 27],
            ["name" => "Wangaratta", "state_id" => 27],
            ["name" => "Wantirna", "state_id" => 27],
            ["name" => "Warragul", "state_id" => 27],
            ["name" => "Warrnambool", "state_id" => 27],
            ["name" => "Welshpool", "state_id" => 27],
            ["name" => "Wendouree", "state_id" => 27],
            ["name" => "Wonthaggi", "state_id" => 27],
            ["name" => "Woodend", "state_id" => 27],
            ["name" => "Yarrawonga-Mulwala", "state_id" => 27],
            ["name" => "Yea", "state_id" => 27],
            ["name" => "Wheeler", "state_id" => 28],
        ]);
    }
}
