<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Timezones extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("timezones")->truncate();
        
        DB::table("timezones")->insert([
            ["timezone" => "Asia/Aden", "offset" => "+03:00"],
            ["timezone" => "Asia/Almaty", "offset" => "+06:00"],
            ["timezone" => "Asia/Amman", "offset" => "+03:00"],
            ["timezone" => "Asia/Anadyr", "offset" => "+12:00"],
            ["timezone" => "Asia/Aqtau", "offset" => "+05:00"],
            ["timezone" => "Asia/Aqtobe", "offset" => "+05:00"],
            ["timezone" => "Asia/Ashgabat", "offset" => "+05:00"],
            ["timezone" => "Asia/Ashkhabad", "offset" => "+05:00"],
            ["timezone" => "Asia/Atyrau", "offset" => "+05:00"],
            ["timezone" => "Asia/Baghdad", "offset" => "+03:00"],
            ["timezone" => "Asia/Bahrain", "offset" => "+03:00"],
            ["timezone" => "Asia/Baku", "offset" => "+04:00"],
            ["timezone" => "Asia/Bangkok", "offset" => "+07:00"],
            ["timezone" => "Asia/Barnaul", "offset" => "+07:00"],
            ["timezone" => "Asia/Beirut", "offset" => "+03:00"],
            ["timezone" => "Asia/Bishkek", "offset" => "+06:00"],
            ["timezone" => "Asia/Brunei", "offset" => "+08:00"],
            ["timezone" => "Asia/Calcutta", "offset" => "+05:30"],
            ["timezone" => "Asia/Chita", "offset" => "+09:00"],
            ["timezone" => "Asia/Choibalsan", "offset" => "+08:00"],
            ["timezone" => "Asia/Chongqing", "offset" => "+08:00"],
            ["timezone" => "Asia/Chungking", "offset" => "+08:00"],
            ["timezone" => "Asia/Colombo", "offset" => "+05:30"],
            ["timezone" => "Asia/Dacca", "offset" => "+06:00"],
            ["timezone" => "Asia/Damascus", "offset" => "+03:00"],
            ["timezone" => "Asia/Dhaka", "offset" => "+06:00"],
            ["timezone" => "Asia/Dili", "offset" => "+09:00"],
            ["timezone" => "Asia/Dubai", "offset" => "+04:00"],
            ["timezone" => "Asia/Dushanbe", "offset" => "+05:00"],
            ["timezone" => "Asia/Famagusta", "offset" => "+03:00"],
            ["timezone" => "Asia/Gaza", "offset" => "+03:00"],
            ["timezone" => "Asia/Harbin", "offset" => "+08:00"],
            ["timezone" => "Asia/Hebron", "offset" => "+03:00"],
            ["timezone" => "Asia/Ho_Chi_Minh", "offset" => "+07:00"],
            ["timezone" => "Asia/Hong_Kong", "offset" => "+08:00"],
            ["timezone" => "Asia/Hovd", "offset" => "+07:00"],
            ["timezone" => "Asia/Irkutsk", "offset" => "+08:00"],
            ["timezone" => "Asia/Istanbul", "offset" => "+03:00"],
            ["timezone" => "Asia/Jakarta", "offset" => "+07:00"],
            ["timezone" => "Asia/Jayapura", "offset" => "+09:00"],
            ["timezone" => "Asia/Jerusalem", "offset" => "+03:00"],
            ["timezone" => "Asia/Kabul", "offset" => "+04:30"],
            ["timezone" => "Asia/Kamchatka", "offset" => "+12:00"],
            ["timezone" => "Asia/Karachi", "offset" => "+05:00"],
            ["timezone" => "Asia/Kashgar", "offset" => "+06:00"],
            ["timezone" => "Asia/Kathmandu", "offset" => "+05:45"],
            ["timezone" => "Asia/Katmandu", "offset" => "+05:45"],
            ["timezone" => "Asia/Khandyga", "offset" => "+09:00"],
            ["timezone" => "Asia/Kolkata", "offset" => "+05:30"],
            ["timezone" => "Asia/Krasnoyarsk", "offset" => "+07:00"],
            ["timezone" => "Asia/Kuala_Lumpur", "offset" => "+08:00"],
            ["timezone" => "Asia/Kuching", "offset" => "+08:00"],
            ["timezone" => "Asia/Kuwait", "offset" => "+03:00"],
            ["timezone" => "Asia/Macao", "offset" => "+08:00"],
            ["timezone" => "Asia/Macau", "offset" => "+08:00"],
            ["timezone" => "Asia/Magadan", "offset" => "+11:00"],
            ["timezone" => "Asia/Makassar", "offset" => "+08:00"],
            ["timezone" => "Asia/Manila", "offset" => "+08:00"],
            ["timezone" => "Asia/Muscat", "offset" => "+04:00"],
            ["timezone" => "Asia/Nicosia", "offset" => "+03:00"],
            ["timezone" => "Asia/Novokuznetsk", "offset" => "+07:00"],
            ["timezone" => "Asia/Novosibirsk", "offset" => "+07:00"],
            ["timezone" => "Asia/Omsk", "offset" => "+06:00"],
            ["timezone" => "Asia/Oral", "offset" => "+05:00"],
            ["timezone" => "Asia/Phnom_Penh", "offset" => "+07:00"],
            ["timezone" => "Asia/Pontianak", "offset" => "+07:00"],
            ["timezone" => "Asia/Pyongyang", "offset" => "+09:00"],
            ["timezone" => "Asia/Qatar", "offset" => "+03:00"],
            ["timezone" => "Asia/Qostanay", "offset" => "+06:00"],
            ["timezone" => "Asia/Qyzylorda", "offset" => "+05:00"],
            ["timezone" => "Asia/Rangoon", "offset" => "+06:30"],
            ["timezone" => "Asia/Riyadh", "offset" => "+03:00"],
            ["timezone" => "Asia/Saigon", "offset" => "+07:00"],
            ["timezone" => "Asia/Sakhalin", "offset" => "+11:00"],
            ["timezone" => "Asia/Samarkand", "offset" => "+05:00"],
            ["timezone" => "Asia/Seoul", "offset" => "+09:00"],
            ["timezone" => "Asia/Shanghai", "offset" => "+08:00"],
            ["timezone" => "Asia/Singapore", "offset" => "+08:00"],
            ["timezone" => "Asia/Srednekolymsk", "offset" => "+11:00"],
            ["timezone" => "Asia/Taipei", "offset" => "+08:00"],
            ["timezone" => "Asia/Tashkent", "offset" => "+05:00"],
            ["timezone" => "Asia/Tbilisi", "offset" => "+04:00"],
            ["timezone" => "Asia/Tehran", "offset" => "+04:30"],
            ["timezone" => "Asia/Tel_Aviv", "offset" => "+03:00"],
            ["timezone" => "Asia/Thimbu", "offset" => "+06:00"],
            ["timezone" => "Asia/Thimphu", "offset" => "+06:00"],
            ["timezone" => "Asia/Tokyo", "offset" => "+09:00"],
            ["timezone" => "Asia/Tomsk", "offset" => "+07:00"],
            ["timezone" => "Asia/Ujung_Pandang", "offset" => "+08:00"],
            ["timezone" => "Asia/Ulaanbaatar", "offset" => "+08:00"],
            ["timezone" => "Asia/Ulan_Bator", "offset" => "+08:00"],
            ["timezone" => "Asia/Urumqi", "offset" => "+06:00"],
            ["timezone" => "Asia/Ust-Nera", "offset" => "+10:00"],
            ["timezone" => "Asia/Vientiane", "offset" => "+07:00"],
            ["timezone" => "Asia/Vladivostok", "offset" => "+10:00"],
            ["timezone" => "Asia/Yakutsk", "offset" => "+09:00"],
            ["timezone" => "Asia/Yangon", "offset" => "+06:30"],
            ["timezone" => "Asia/Yekaterinburg", "offset" => "+05:00"],
            ["timezone" => "Asia/Yerevan", "offset" => "+04:00"],
            ["timezone" => "Australia/ACT", "offset" => "+11:00"],
            ["timezone" => "Australia/Adelaide", "offset" => "+10:30"],
            ["timezone" => "Australia/Brisbane", "offset" => "+10:00"],
            ["timezone" => "Australia/Broken_Hill", "offset" => "+10:30"],
            ["timezone" => "Australia/Canberra", "offset" => "+11:00"],
            ["timezone" => "Australia/Currie", "offset" => "+11:00"],
            ["timezone" => "Australia/Darwin", "offset" => "+09:30"],
            ["timezone" => "Australia/Eucla", "offset" => "+08:45"],
            ["timezone" => "Australia/Hobart", "offset" => "+11:00"],
            ["timezone" => "Australia/LHI", "offset" => "+11:00"],
            ["timezone" => "Australia/Lindeman", "offset" => "+10:00"],
            ["timezone" => "Australia/Lord_Howe", "offset" => "+11:00"],
            ["timezone" => "Australia/Melbourne", "offset" => "+11:00"],
            ["timezone" => "Australia/North", "offset" => "+09:30"],
            ["timezone" => "Australia/NSW", "offset" => "+11:00"],
            ["timezone" => "Australia/Perth", "offset" => "+08:00"],
            ["timezone" => "Australia/Queensland", "offset" => "+10:00"],
            ["timezone" => "Australia/South", "offset" => "+10:30"],
            ["timezone" => "Australia/Sydney", "offset" => "+11:00"],
            ["timezone" => "Australia/Tasmania", "offset" => "+11:00"],
            ["timezone" => "Australia/Victoria", "offset" => "+11:00"],
            ["timezone" => "Australia/West", "offset" => "+08:00"],
            ["timezone" => "Australia/Yancowinna", "offset" => "+10:30"]
        ]);
    }
}
